/* Throwing exception without catching it */
main {
    Exception("My exception");
}
